// configurations
const config = require('../../../../config/config');

// external modules
const router = require('express').Router();
const handlebars = require('handlebars');
const path = require('path');
const fs = require('fs');
const url = require('url');
const cors = require('cors');

// internal modules
// const KafkaProducer = require('../../../../lib/kafka-producer');
const validator = require('../../../../lib/schema-validator')({
    userActivitySchema: require('../../schemas/user-activity-schema')
});

// TODO: initialize kafka producer
// const producer = new KafkaProducer(config.kafka);

/**
 * @description Adds API routes for logging user activity.
 * @param {Object} pg - Postgres connection wrapper.
 * @param {Object} logger - The logger object.
 */
module.exports = function (pg, logger) {
    // parameters used within the routes
    const x5gonCookieName = 'x5gonTrack';

    /**
     * @api {GET} /api/v1/snippet/tracker On-premise user cookie generation
     * @apiDescription Sets the user cookie if repository uses the on-premise
     * snippet version
     * @apiPrivate The API is meant to be be used in combination with the on-premise snippet version.
     * @apiName GetSnippetTracker
     * @apiGroup UserActivity
     * @apiVersion 1.0.0
     *
     * @apiParam {String} callbackURL - The URL to which the tracker will redirect once the cookie
     * is set.
     *
     * @apiParamExample {json} User Activity Information:
     *  {
     *      "callbackURL": "https://platform.x5gon.org/redirect",
     *  }
     */
    router.get('/snippet/tracker', (req, res) => {
        // TODO: validate the parameters

        // get query parameters
        let query = req.query;
        // create a handlebars compiler
        let activityTracker = fs.readFileSync(path.join(__dirname, '../../snippet/templates/tracker.hbs'));
        let hbs = handlebars.compile(activityTracker.toString('utf-8'));

        // send the website with cookie generation
        return res.send(hbs({ callbackURL: query.callbackURL, x5gonCookieName }));
    });

    /**
     * @api {GET} /api/v1/snippet/log User activity acquisition
     * @apiDescription Send user activity snippet information. All parameters should
     * be encoded by the `encodeURIComponent` function
     * @apiName GetSnippetLog
     * @apiGroup UserActivity
     * @apiVersion 1.0.0
     *
     * @apiParam {Boolean} x5gonValidated - Notifies if the user is validated by the X5GON platform.
     * @apiParam {String} dt - The URI date-time.
     * @apiParam {String} rq - The URL from which the request was sent.
     * @apiParam {String} rf - The referrer URL.
     * @apiParam {String} cid - The provider token generated by the X5GON platform.
     * @apiParam {Boolean} [test=false] - Notifies if the request was sent to test the snippet integration.
     *
     * @apiParamExample {json} User Activity Information:
     *  {
     *    "x5gonValidated": true,
     *    "dt": "2018-10-04T10%3A19%3A45Z",
     *    "rq": "https://platform.x5gon.org/example",
     *    "rf": null,
     *    "cid": "x5gonTokenXYZ",
     *    "test": true
     *  }
     *
     * @apiSuccessExample {text} Success-Response:
     *  HTTP/1.1 200 OK Image of a pixel with the following headers:
     *      "x-snippet-status": "success"
     *      "x-snippet-message": null
     *
     * @apiErrorExample {text} Error-Response:
     *  HTTP/1.1 200 OK Image of a pixel with the following headers:
     *      "x-snippet-status": "failure"
     *      "x-snippet-message": "check if all parameters are set and if the date-time is in the correct format"
     */
    router.get('/snippet/log', (req, res) => {
        // check and convert to boolean
        const testing = req.query.test === 'true' || false;
        if (testing) {
            // development environment
            res.redirect(url.format({
                pathname: '/api/v1/snippet/log/development',
                query: req.query
            }));
        } else {
            // production environment
            res.redirect(url.format({
                pathname: '/api/v1/snippet/log/production',
                query: req.query
            }));
        }
    });

    /**
     * @description Validates the user requests and returns the options/headers for the beacon image
     * & the user parameters
     * @param {Object} req - The express request object.
     * @returns {Object} The options and user parameters.
     * @private
     */
    function _evaluateLog(req) {
        // get query parameters
        let userParameters = { };

        userParameters.x5gonValidated = decodeURIComponent(req.query.x5gonValidated);
        userParameters.dt = decodeURIComponent(req.query.dt);
        userParameters.rq = decodeURIComponent(req.query.rq);
        userParameters.rf = decodeURIComponent(req.query.rf);
        userParameters.cid = decodeURIComponent(req.query.cid);

        // set the snippet status headers
        // notifying the user about the success or failure
        let options = {
            headers: {
                'x-snippet-date': new Date(),
                'x-snippet-status': 'success',
                'x-snippet-message': null
            }
        };

        // validate query schema
        if (!Object.keys(userParameters).length ||
            !validator.validateSchema(userParameters, validator.schemas.userActivitySchema)) {
            options.headers['x-snippet-status'] = 'failure';
            // TODO: add a good description of what went wrong
            options.headers['x-snippet-message'] = 'check if all parameters are set and if the date-time is in the correct format';
        }
        // return options and user parameters
        return { options, userParameters };
    }

    /**
     * @api {GET} /api/v1/snippet/log/development User activity acquisition for testing
     * @apiDescription Sends user activity snippet information FOR TESTING.
     * All parameters should be encoded by the `encodeURIComponent` function
     * @apiName GetSnippetLogDevelopment
     * @apiGroup UserActivity
     * @apiVersion 1.0.0
     *
     * @apiPrivate The API is meant to be used through the `/api/v1/snippet/log`
     *
     * @apiParam {Boolean} x5gonValidated - Notifies if the user is validated by the X5GON platform.
     * @apiParam {String} dt - The URI date-time.
     * @apiParam {String} rq - The URL from which the request was sent.
     * @apiParam {String} rf - The referrer URL.
     * @apiParam {String} cid - The provider token generated by the X5GON platform.
     * @apiParam {Boolean} [test=false] - Notifies if the request was sent to test the snippet integration.
     *
     * @apiParamExample {json} User Activity Information:
     *  {
     *    "x5gonValidated": true,
     *    "dt": "2018-10-04T10%3A19%3A45Z",
     *    "rq": "https://platform.x5gon.org/example",
     *    "rf": null,
     *    "cid": "x5gonTokenXYZ",
     *    "test": true
     *  }
     */
    router.get('/snippet/log/development', (req, res) => {
        // the beacon used to acquire user activity data
        let beaconPath = path.join(__dirname, '../../snippet/images/beacon.png');
        // get the options - snippet status headers
        const { options } = _evaluateLog(req);
        // send beacon image to user
        return res.sendFile(beaconPath, options);
    });

    /**
     * @api {GET} /api/v1/snippet/log/production User activity acquisition for production
     * @apiDescription Sends user activity snippet information FOR PRODUCTION.
     * All parameters should be encoded by the `encodeURIComponent` function
     * @apiName GetSnippetLogProduction
     * @apiGroup UserActivity
     * @apiVersion 1.0.0
     *
     * @apiPrivate The API is meant to be used through the `/api/v1/snippet/log`
     *
     * @apiParam {Boolean} x5gonValidated - Notifies if the user is validated by the X5GON platform.
     * @apiParam {String} dt - The URI date-time.
     * @apiParam {String} rq - The URL from which the request was sent.
     * @apiParam {String} rf - The referrer URL.
     * @apiParam {String} cid - The provider token generated by the X5GON platform.
     * @apiParam {Boolean} [test=false] - Notifies if the request was sent to test the snippet integration.
     *
     * @apiParamExample {json} User Activity Information:
     *  {
     *    "x5gonValidated": true,
     *    "dt": "2018-10-04T10%3A19%3A45Z",
     *    "rq": "https://platform.x5gon.org/example",
     *    "rf": null,
     *    "cid": "x5gonTokenXYZ",
     *    "test": true
     *  }
     */
    router.get('/snippet/log/production', (req, res) => {
        // log client activity
        logger.info('client requested activity logging',
            logger.formatRequest(req)
        );

        // the beacon used to acquire user activity data
        let beaconPath = path.join(__dirname, '../../snippet/images/beacon.png');
        // get the options - snippet status headers
        const { options, userParameters } = _evaluateLog(req);
        // validate query schema
        if (options.headers['x-snippet-status'] === 'failure') {
            // the user parameters object is either empty or is not in correct schema
            const provider = userParameters.cid ? userParameters.cid : 'unknown';
            // log user parameters error
            logger.error('error [route_body]: client activity logging failed',
                logger.formatRequest(req, {
                    error: 'The body of the request is not in valid schema',
                    provider

                })
            );
            // send beacon image to user
            return res.sendFile(beaconPath, options);
        }

        // get the user id from the X5GON tracker
        let uuid = req.cookies[x5gonCookieName] ?
            req.cookies[x5gonCookieName] :
            'unknown:not-tracking';

        // prepare the acitivity object
        let activity = {
            uuid: uuid,
            provider: userParameters.cid,
            url: userParameters.rq,
            referrer: userParameters.rf,
            visitedOn: userParameters.dt,
            userAgent: req.get('user-agent'),
            language: req.get('accept-language')
        };

        // store the client activity into postgres
        pg.insert(activity, 'client_activity', (error) => {
            if (error) {
                // log postgres error
                logger.error('error [postgres.insert]: client activity logging failed',
                    logger.formatRequest(req, { error: error.message })
                );
            } else {
                // redirect activity to information retrievers
                // producer.send('retrieval-topic', activity);
                // log postgres success
                logger.info('client activity logging successful',
                    logger.formatRequest(req)
                );
            }
            // send beacon image to user
            return res.sendFile(beaconPath, options);
        });
    });

    /**
     * @api {GET} /api/v1/snippet/:version/x5gon-log(.min)?.js User activity acquisition library
     * @apiDescription Gets the snippet library directly from the server
     * @apiName GetSnippetLibrary
     * @apiGroup UserActivity
     * @apiVersion 1.0.0
     *
     * @apiParam {String="v1","v2","latest"} version - The version of the library.
     *
     * @apiExample {html} Example usage:
     *      <script type="text/javascript" src="https://platform.x5gon.org/api/v1/snippet/latest/x5gon-log.min.js"></script>
     */
    router.get('/snippet/:version/x5gon-log(.min)?.js', cors(), (req, res) => {
        // TODO: check if the parameters are valid

        // get the version parameter
        const version = req.params.version;

        // get the file name
        let originalUrl = req.originalUrl.split('/');
        const file = originalUrl[originalUrl.length - 1].split('?')[0];
        // create the file path
        const filePath = path.join(__dirname, `../../snippet/global/${version}/${file}`);

        // generate a the tracker cookie - if not exists
        if (!req.cookies[x5gonCookieName]) {
            // generate the cookie value
            let cookieValue = Math.random().toString().substr(2) + "X" + Date.now();
            // set expiration date for the cookie
            let expirationDate = new Date();
            expirationDate.setDate(expirationDate.getDate() + 3650);
            // set the cookie for the user
            res.cookie(x5gonCookieName, cookieValue, { expires: expirationDate, httpOnly: true });
        }

        // send the file of the appropriate version
        res.sendFile(filePath);
    });

    return router;
};